### ISSUE TITLE
Get and store the MagicSeaweed api key in an environment variable

### ISSUE THREAD

**Issue by avenmia** [kmal808/go-or-no#6]
This task is for obtaining an api key for the magic seaweed api and adding it to the application.

https://magicseaweed.com/docs/developers/59/terms-and-conditions/9906/

Once we get the key we should store the key in an environment variable.

See the following commit for how to define the types for adding a new environment variable.
https://github.com/kmal808/go-or-no/pull/3/commits/4bbe979f2b48238776460b35a887cbfe775fe65f

Add a .env file and define an environment variable. The environment variable must be prefixed with "PUBLIC_"
For Example:
 
```
PUBLIC_SEAWEED_APIKEY={key}
```

**Comment by kmal808** [comment]
Sign up link [here](https://magicseaweed.com/docs/developers/59/querying-the-api/9909/) is not clickable. 

<img width="971" alt="MSW API Application Link Not Available" src="https://user-images.githubusercontent.com/20919083/189544162-5de5d53e-1dbb-46a4-b149-e5e1be84fe4d.png">

Will need to find another path to applying for key.

**Comment by kmal808** [comment]
The Wayback machine to the rescue. 
<img width="992" alt="Screen Shot 2022-09-11 at 11 20 23 AM" src="https://user-images.githubusercontent.com/20919083/189549341-42239759-09c9-4a65-a136-1158648d795e.png">

**Comment by kmal808** [comment]
Gonna close this issue since the MSW API key isn't the route for data anymore.
